# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nu-plugin-from-parquet = {
    pname = "nu-plugin-from-parquet";
    version = "6ad980ca96b45c9e1856496ec83f9aa2d65b35fc";
    src = fetchFromGitHub {
      owner = "fdncred";
      repo = "nu_plugin_from_parquet";
      rev = "6ad980ca96b45c9e1856496ec83f9aa2d65b35fc";
      fetchSubmodules = false;
      sha256 = "sha256-VJorURnEl6jdsSsDYtUX3hBcovdyABjTkVESZki+slw=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./nu-plugin-from-parquet-6ad980ca96b45c9e1856496ec83f9aa2d65b35fc/Cargo.lock;
      outputHashes = {
        
      };
    };
    date = "2023-06-21";
  };
  nu-plugin-regex = {
    pname = "nu-plugin-regex";
    version = "06b9aada8df0272bb7500e13f0f611f345c0e0b3";
    src = fetchFromGitHub {
      owner = "fdncred";
      repo = "nu_plugin_regex";
      rev = "06b9aada8df0272bb7500e13f0f611f345c0e0b3";
      fetchSubmodules = false;
      sha256 = "sha256-5x7esBRwmysi0ZVcxFuC9RiHllXlWDe8h02yQSQjEIw=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./nu-plugin-regex-06b9aada8df0272bb7500e13f0f611f345c0e0b3/Cargo.lock;
      outputHashes = {
        
      };
    };
    date = "2023-04-10";
  };
}
