default:
    echo "Hello Tenzir Cell"

@all:
    std run //tenzir//entrypoints:docker-compose-vast-prod
    std run //tenzir//entrypoints:config-vast-prod
    std run //tenzir//entrypoints:nomad-node-prod
    std run //tenzir//entrypoints:nomad-opencti-dev

@container:
    std run //tenzir//entrypoints:podman-vast-latest-prod
    std run //tenzir//entrypoints:podman-vast-release-prod
