[entryPoints]

[entryPoints.web]
address = ":8901"

[entryPoints.websecure]
address = ":8902"

[entryPoints.traefik]
address = ":8909"

[api]
dashboard = true
insecure = true

# Enable Consul Catalog configuration backend.
[providers.consulCatalog]
# create endpoint for service tag starting by npiatto-generic-http-ingress
prefix = "http-ingress-connect"
# Do not expose/create route by default, it must be explicitly enable at
# the service level
exposedByDefault = false
# Enable consul-connect support
connectAware = true
# Use secure connection / mTLS by default
connectbydefault = true
# Register this service in consul, must match the service stanza name to
# allow the user to create the consul-intention
serviceName = "http-ingress-connect"

[providers.file]
directory = "local/traefik/"
watch = "true"

[tls.stores]

[tls.stores.default]

# Enable Logging (default is to stdout)
[accessLog]

[log]
level = "debug"
format = "json"
